###
POST http://localhost:3000/auth/register/
Content-Type: application/json

{
  "email": "pepe7@pepe.es",
  "password": "pepe123",
  "name": "Pepe" 
}

###
POST http://localhost:3000/auth/login/
Content-Type: application/json

{
  "email": "pepe5@pepe.es",
  "password": "pepe123"
}

###
GET http://localhost:3000/auth/google/




###


POST https://crudbackend-pink.vercel.app/auth/register/
Content-Type: application/json

{
  "email": "pepe5@pepe.es",
  "password": "pepe123",
  "name": "Pepe" 
}


###
GET https://crudbackend-pink.vercel.app/env-check

###
GET https://crudbackend-pink.vercel.app/hola

###
GET http://localhost:3000/hola

###
GET http://localhost:3000/env-check


###
GET https://crudbackend-pink.vercel.app/hola

###
GET https://crudbackend-pink.vercel.app/env-check